# Environment Configuration for Nobody Knows Podcast Production
# This file centralizes environment-specific settings to avoid hardcoded values

environment:
  name: "production"
  debug: false

paths:
  project_root: "${CLAUDE_PROJECT_ROOT:-.}"
  sessions_dir: "${PROJECT_ROOT}/.claude/level-2-production/sessions"
  output_dir: "${PROJECT_ROOT}/projects/nobody-knows/output"
  agents_dir: "${PROJECT_ROOT}/.claude/level-2-production/agents"
  commands_dir: "${PROJECT_ROOT}/.claude/level-2-production/commands"
  tools_dir: "${PROJECT_ROOT}/.claude/level-2-production/tools"
  templates_dir: "${PROJECT_ROOT}/.claude/level-2-production/templates"
  config_dir: "${PROJECT_ROOT}/.claude/level-2-production/config"
  audio_output: "${PROJECT_ROOT}/audio-output"

episode_settings:
  duration_minutes: 30
  target_word_count: 4250  # ~142 words per minute
  min_word_count: 4000
  max_word_count: 4500

quality_thresholds:
  comprehension: 0.85
  brand_consistency: 0.90
  engagement: 0.80
  technical_accuracy: 0.85
  minimum_acceptable: 0.75

cost_limits:
  target_per_episode: 4.00
  maximum_per_episode: 5.00
  warning_threshold: 4.50

retry_settings:
  max_retries: 3
  base_delay_seconds: 5
  max_delay_seconds: 60
  backoff_multiplier: 2

mcp_servers:
  perplexity:
    enabled: "${PERPLEXITY_API_KEY:-false}"
    command: "perplexity-mcp"
    required: true
  elevenlabs:
    enabled: "${ELEVENLABS_API_KEY:-false}"
    command: "elevenlabs-mcp"
    required: false

models:
  primary: "claude-3-5-sonnet-20241022"
  secondary: "gemini-pro"  # Placeholder for when available
  fallback: "claude-3-haiku-20240307"

session_management:
  retention_days: 30
  backup_frequency: "after_checkpoint"
  auto_cleanup: true

logging:
  level: "INFO"
  format: "{timestamp} [{level}] {agent} - {message}"
  error_retention_days: 30
  success_retention_days: 7
  checkpoint_retention_days: 14

brand_voice:
  keywords:
    - "nobody knows"
    - "we don't fully understand"
    - "remains mysterious"
    - "still learning"
    - "open questions"
  target_humility_score: 0.85
  minimum_questions_per_episode: 10

api_endpoints:
  # These are placeholders - actual values come from environment
  perplexity: "${PERPLEXITY_API_URL:-https://api.perplexity.ai}"
  elevenlabs: "${ELEVENLABS_API_URL:-https://api.elevenlabs.io}"

# Runtime validation
validation:
  check_on_startup:
    - paths_exist
    - mcp_connectivity
    - git_clean_state
    - sufficient_disk_space
  minimum_disk_gb: 1.0

# Hooks configuration (if hooks are enabled)
hooks:
  enabled: true
  pre_production: ".claude/hooks/pre-production.sh"
  post_agent: ".claude/hooks/post-agent.sh"
  quality_failure: ".claude/hooks/quality-failure.sh"
  session_complete: ".claude/hooks/session-complete.sh"
