# Episode Configuration
# Defines default settings for podcast episode production

episode_defaults:
  target_length: "4000-4500"  # words
  complexity_level: 5  # 1-10 scale
  format: "conversational"
  tone: "curious"

intellectual_humility:
  target_percentage: 8.0  # minimum percentage of text
  required_phrases:
    - "I don't know"
    - "Perhaps"
    - "It's possible"
    - "I wonder"
    - "What if"
    - "Maybe"
    - "Could be"

quality_requirements:
  min_comprehension_score: 0.85
  min_brand_consistency: 0.90
  min_engagement_score: 0.80
  min_technical_accuracy: 0.85

production_limits:
  max_retries: 3
  timeout_minutes: 15
  max_cost_per_episode: 5.00
