# Simple Error Handling Configuration
# Defines what to do when common errors occur

error_types:
  # Network/API errors - just try again
  transient:
    description: "Temporary problems that usually fix themselves"
    examples:
      - "Network timeout"
      - "API rate limit"
      - "Service temporarily unavailable"
    action: "retry"
    max_retries: 3
    wait_between_retries: 10  # seconds

  # Quality issues - try to fix the content
  quality:
    description: "Content doesn't meet our standards"
    examples:
      - "Comprehension score too low"
      - "Not enough brand voice"
      - "Too technical for audience"
    action: "revise"
    max_revisions: 2
    use_agent: "script_polisher"

  # Setup problems - need human help
  configuration:
    description: "Something is not set up correctly"
    examples:
      - "Missing API key"
      - "File not found"
      - "Permission denied"
    action: "stop_and_notify"
    message: "Please check your setup"

  # Big problems - stop everything
  critical:
    description: "Serious errors that we can't fix automatically"
    examples:
      - "Out of disk space"
      - "System crash"
      - "Data corruption"
    action: "emergency_stop"
    save_state: true
    notify: "immediate"

# Simple quality thresholds
quality_gates:
  minimum_scores:
    comprehension: 0.85      # Easy to understand
    brand_consistency: 0.90  # Sounds like "Nobody Knows"
    engagement: 0.80         # Interesting to listen to
    technical_accuracy: 0.85 # Facts are correct

# Retry settings
retry_policy:
  delays: [5, 10, 30]  # seconds between retries
  max_total_time: 300  # 5 minutes max

# Where to save error logs
logging:
  error_log: ".claude/level-2-production/logs/errors.log"
  recovery_log: ".claude/level-2-production/logs/recovery.log"
  keep_logs_for_days: 30
