# MASTER CONFIGURATION - SINGLE SOURCE OF TRUTH
# Nobody Knows Podcast Production System v3.0.0
# This file is the AUTHORITATIVE configuration source
# ALL other configurations must reference values from this file

metadata:
  version: "3.0.0"
  last_updated: "2025-01-14"
  authority: "MASTER_CONFIG"
  schema_version: "1.0"
  config_hash_cmd: "sha256sum production-config.yaml | cut -d' ' -f1"

# =============================================================================
# EPISODE SPECIFICATIONS - CONSOLIDATED FROM MULTIPLE SOURCES
# =============================================================================
episode:
  duration:
    target_minutes: 28  # Consolidated from conflicting 27/30/25-30/47 values
    min_minutes: 25     # Minimum acceptable duration
    max_minutes: 30     # Maximum acceptable duration
    tolerance_minutes: 1 # Acceptable variance from target

  content:
    words:
      target: 4200      # 28 min * 150 WPM baseline
      min: 3750         # 25 min * 150 WPM
      max: 4650         # 31 min * 150 WPM (includes tolerance)
      wpm_baseline: 150 # Words per minute speaking rate

    characters:
      target: 21000     # 4200 words * 5 chars/word average
      min: 18750        # 3750 words * 5 chars/word
      max: 23250        # 4650 words * 5 chars/word
      chars_per_word: 5 # Average character density

  audio:
    file_size_mb:
      target: 30        # Estimated for 28-minute episode
      min: 25          # For 25-minute episode
      max: 35          # For 30-minute episode + tolerance

    format: "mp3_44100_128"
    sample_rate: 44100
    bitrate: 128
    channels: "mono"

# =============================================================================
# API PROVIDER CONFIGURATIONS - CONSOLIDATED
# =============================================================================
apis:
  elevenlabs:
    model:
      id: "eleven_turbo_v2_5"
      name: "Turbo v2.5"
      display_name: "ElevenLabs Turbo v2.5"
      quality_focus: "high"     # Quality over speed
      latency_ms: 275          # Average 250-300ms

    voice:
      primary:
        name: "Amelia"
        id: "ZF6FPAbjXT4488VcRRnw"
        description: "young and enthusiastic"
        characteristics: "warm, intellectual delivery"
      backup:
        name: "Rachel"
        fallback_when: "primary_unavailable"

    pricing:
      rate: 0.30                # USD per 1k characters
      unit: "usd_per_1k_chars"
      credits_per_char: 0.0005  # 0.5 credits per character
      estimated_episode_cost: 6.30  # 21k chars * $0.30

    settings:
      stability: 0.5            # Balance consistency/expressiveness
      similarity_boost: 0.75    # Voice matching strength
      style: 0.3               # Slight style enhancement
      use_speaker_boost: true
      speed: 1.0               # Normal speaking pace
      language: "en"
      enable_ssml_parsing: true # REQUIRED for SSML tags

    technical:
      max_characters_single_call: 500000
      recommended_single_call: true
      timeout_minutes: 25       # For long audio synthesis
      retry_attempts: 3

  perplexity:
    model:
      primary: "sonar-pro"
      backup: "sonar"

    rate_limits:
      requests_per_minute: 60
      requests_per_day: 5000
      concurrent_requests: 5

    pricing:
      rate: 0.001              # USD per 1k tokens (estimated)
      unit: "usd_per_1k_tokens"
      estimated_per_research: 2.50

    settings:
      timeout_seconds: 30
      max_retries: 3
      backoff_multiplier: 2

  claude:
    models:
      primary: "claude-3-5-sonnet-20241022"
      secondary: "claude-3-5-sonnet-20240620"
      fallback: "claude-3-haiku-20240307"
      quality_model: "claude-3-5-sonnet-20241022"  # For quality evaluation

    pricing:
      sonnet_input: 3.00       # USD per million tokens
      sonnet_output: 15.00     # USD per million tokens
      haiku_input: 0.25        # USD per million tokens
      haiku_output: 1.25       # USD per million tokens

    settings:
      max_tokens: 4096
      temperature: 0.3         # Consistent, focused responses
      timeout_seconds: 60

  gemini:
    model: "gemini-pro"
    pricing:
      free_tier: true          # Currently free
      estimated_cost: 0.00
    settings:
      temperature: 0.3
      max_output_tokens: 2048
      timeout_seconds: 45

# =============================================================================
# COST CONTROL SYSTEM - CONSOLIDATED FROM MULTIPLE SOURCES
# =============================================================================
costs:
  per_episode:
    target: 6.30              # Realistic based on actual content size
    maximum: 8.00             # Hard limit - pipeline halt
    alert_threshold: 7.50     # Warning threshold
    budget_buffer: 1.70       # Maximum - target

  agent_budgets:
    01_research_coordinator: 2.50    # Perplexity + Claude research
    02_episode_planner: 0.25         # Planning and coordination
    03_script_writer: 1.75           # Script generation
    04_quality_claude: 0.50          # Quality evaluation
    05_quality_gemini: 0.00          # Free tier
    06_feedback_synthesizer: 0.25    # Feedback processing
    07_tts_optimizer: 0.75           # TTS preparation
    08_final_reviewer: 0.25          # Final validation
    09_audio_synthesizer: 6.30       # ElevenLabs TTS (major cost)

  checkpoint_savings:
    per_checkpoint: 6.30      # Audio synthesis checkpoint value
    total_possible: 12.60     # If all checkpoints hit

  tracking:
    log_all_costs: true
    cost_per_token: true
    monthly_budget: 500.00    # Overall system budget
    alert_percentage: 80      # Alert at 80% of monthly

# =============================================================================
# QUALITY GATES - AUTHORITATIVE THRESHOLDS
# =============================================================================
quality:
  thresholds:
    comprehension:
      minimum: 0.85           # Must exceed for publication
      target: 0.90            # Quality goal
      weight: 0.25           # Importance in overall score
      description: "General audience understanding without technical background"

    brand_consistency:
      minimum: 0.90           # Core brand requirement
      target: 0.95            # Brand excellence
      weight: 0.30           # Highest importance
      description: "Nobody Knows brand voice and intellectual humility"

    engagement:
      minimum: 0.80           # Listener retention requirement
      target: 0.85            # Engagement goal
      weight: 0.20           # Audience experience
      description: "Maintains interest for full episode duration"

    technical_accuracy:
      minimum: 0.85           # Factual correctness requirement
      target: 0.92            # Technical excellence
      weight: 0.25           # Critical for credibility
      description: "Factual correctness and proper explanations"

  evaluation:
    models:
      claude: 0.55            # Primary evaluator weight
      gemini: 0.45            # Secondary evaluator weight

    consensus:
      max_difference: 0.15    # Escalate if scores differ more
      agreement_threshold: 0.10  # Good agreement threshold

    revision_triggers:
      minor_revision: 0.05    # Score gap triggering minor revision
      major_revision: 0.10    # Score gap triggering major revision
      complete_rewrite: 0.60  # Minimum acceptable score

  brand_voice:
    intellectual_humility:
      target_instances: 5     # Per episode
      minimum_instances: 3    # Minimum acceptable
      phrases:
        - "nobody knows"
        - "we don't fully understand"
        - "remains mysterious"
        - "still learning"
        - "honestly, we're not sure"
        - "the truth is, it's complicated"

    question_density:
      per_1000_words: 4       # Target curiosity questions
      minimum_per_1000: 2     # Minimum engagement
      types:
        - curiosity_prompts
        - technical_questions
        - philosophical_implications
        - audience_engagement

    feynman_analogies:
      target_per_episode: 5   # Clear explanations
      minimum_per_episode: 3  # Basic requirement
      criteria:
        - everyday_objects: true
        - builds_progressively: true
        - avoids_nested_complexity: true

# =============================================================================
# FILE PATHS AND PROJECT STRUCTURE
# =============================================================================
paths:
  project_root: "${CLAUDE_PROJECT_ROOT:-.}"
  level_2_base: ".claude/level-2-production"

  directories:
    sessions: ".claude/level-2-production/sessions"
    agents: ".claude/level-2-production/agents"
    commands: ".claude/level-2-production/commands"
    tools: ".claude/level-2-production/tools"
    config: ".claude/level-2-production/config"
    templates: ".claude/level-2-production/templates"
    output: "projects/nobody-knows/output"
    audio_output: "projects/nobody-knows/output/audio"

  templates:
    session_template: "templates/session-template.json"
    checkpoint_template: "templates/checkpoint-template.json"
    handoff_template: "templates/handoff-template.md"

  logging:
    cost_tracking: ".claude/logs/api_costs.csv"
    error_log: ".claude/logs/errors.log"
    session_log: ".claude/logs/sessions.log"

# =============================================================================
# SSML AND TTS OPTIMIZATION SETTINGS
# =============================================================================
tts_optimization:
  ssml:
    enabled: true
    parsing_required: true    # enable_ssml_parsing=True
    approach: "minimal_contextual"

    tags:
      break_tags: "natural_pauses"     # Contextual breathing spaces
      emphasis_tags: "key_concepts"    # Important terms only
      prosody_tags: "complex_terms"    # Slight rate reduction

    restrictions:
      no_custom_markup: true          # No [curious], [thoughtful] tags
      no_excessive_tags: true         # Minimal intervention
      neural_friendly: true           # Let AI handle naturally

  content_preparation:
    approach: "clean_extraction"      # Remove all metadata
    remove_headers: true              # No production notes in audio
    remove_formatting: true           # Clean text only
    normalize_pronunciation: true     # Technical terms

  optimization_level: "neural_friendly"  # Minimal intervention for 2025 models

# =============================================================================
# SYSTEM CONFIGURATION
# =============================================================================
system:
  environment: "production"
  debug: false

  session_management:
    retention_days: 30
    backup_frequency: "after_checkpoint"
    auto_cleanup: true
    checkpoint_validation: true

  retry_policies:
    max_attempts: 3
    base_delay_seconds: 5
    max_delay_seconds: 60
    backoff_multiplier: 2
    timeout_minutes: 45

  validation:
    check_on_startup:
      - config_file_exists
      - required_paths_exist
      - api_connectivity
      - mcp_servers_available
      - sufficient_disk_space

    minimum_disk_gb: 2.0
    config_schema_validation: true

  monitoring:
    cost_tracking: true
    performance_metrics: true
    quality_trends: true
    configuration_drift_detection: true

  hooks:
    enabled: true
    pre_production: ".claude/hooks/pre-production.sh"
    post_agent: ".claude/hooks/post-agent.sh"
    config_validation: ".claude/hooks/config-validation.sh"
    session_complete: ".claude/hooks/session-complete.sh"

# =============================================================================
# PROGRESSIVE COMPLEXITY BY SEASON
# =============================================================================
complexity_progression:
  season_1:
    episodes: [1, 25]
    complexity_range: [1, 3]
    focus: "fundamental_concepts"
    target_audience: "beginners"

  season_2:
    episodes: [26, 50]
    complexity_range: [3, 5]
    focus: "building_understanding"
    target_audience: "intermediate"

  season_3:
    episodes: [51, 75]
    complexity_range: [5, 7]
    focus: "technical_depth"
    target_audience: "advanced"

  season_4:
    episodes: [76, 100]
    complexity_range: [7, 9]
    focus: "cutting_edge_research"
    target_audience: "expert"

  season_5:
    episodes: [101, 125]
    complexity_range: [8, 10]
    focus: "philosophical_implications"
    target_audience: "thought_leaders"

# =============================================================================
# VALIDATION AND COMPLIANCE
# =============================================================================
validation_rules:
  configuration:
    all_thresholds_sum_to_1: true
    minimum_below_targets: true
    cost_budgets_within_maximum: true
    complexity_ranges_progressive: true
    required_fields_present: true

  runtime_checks:
    config_hash_verification: true
    drift_detection: true
    compliance_auditing: true
    hardcoded_value_blocking: true

  enforcement:
    pre_commit_hooks: true
    runtime_validation: true
    periodic_audits: true
    violation_blocking: true

# =============================================================================
# CHANGE MANAGEMENT
# =============================================================================
change_control:
  config_modifications:
    requires_review: true
    version_increment: true
    migration_plan: true
    rollback_strategy: true

  deployment:
    testing_required: true
    staged_rollout: true
    monitoring_period_hours: 24
    automatic_rollback_triggers: true

# =============================================================================
# LEGACY CLEANUP TARGETS
# =============================================================================
deprecation:
  files_to_remove:
    - "config/episode-config.yaml"    # Replaced by this master config
    - "config/tts-config.yaml"        # Consolidated into this file
    - "config/environment.yaml"       # Consolidated into this file

  hardcoded_values_to_eliminate:
    - "47.minute.*episodes"
    - "35k.*character"
    - "\\$[0-9]+\\.[0-9]+"              # Hardcoded costs
    - "eleven_flash_v2_5"             # Old model references
    - "ZF6FPAbjXT4488VcRRnw"          # Hardcoded voice IDs (use config)

  migration_targets:
    agents: 10                        # Agent files to migrate
    tools: 15                         # Tool scripts to migrate
    sessions: 50                      # Session files to update
    commands: 5                       # Command files to migrate

# END OF MASTER CONFIGURATION
# All system components must reference values from this file
# Direct hardcoding of these values is prohibited
