#!/bin/bash
# Session Completion Hook
# Automatically commits work and creates session summary

echo "📝 Session Completion Hook Triggered"
echo "===================================="

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

TIMESTAMP=$(date +%Y%m%d_%H%M)
SESSION_ID="session_${TIMESTAMP}"

# 1. Check for changes
echo -n "Checking for changes... "
if git diff-index --quiet HEAD -- 2>/dev/null; then
    echo -e "${GREEN}No uncommitted changes${NC}"
else
    echo -e "${YELLOW}Found uncommitted changes${NC}"

    # Show what changed
    echo ""
    echo "Files changed:"
    git status --short

    # Add all changes
    echo ""
    echo -n "Staging changes... "
    git add -A
    echo -e "${GREEN}Done${NC}"

    # Create commit
    echo -n "Creating commit... "
    git commit -m "session: auto-commit at session end ${TIMESTAMP}" >/dev/null 2>&1
    echo -e "${GREEN}Done${NC}"
fi

# 2. Show recent commits
echo ""
echo "Recent commits:"
git log --oneline -5

# 3. Create session summary
SUMMARY_FILE=".claude/sessions/summaries/${SESSION_ID}_summary.md"
mkdir -p .claude/sessions/summaries

cat > "$SUMMARY_FILE" << EOF
# Session Summary: ${SESSION_ID}
Generated: $(date)

## Git Status
$(git status --short)

## Recent Commits
$(git log --oneline -10)

## Work Completed
- Check todo list for completed items
- Review git log for changes

## Next Steps
- Continue with pending todos
- Run integration tests
- Validate quality gates

---
*Auto-generated by session-complete hook*
EOF

echo ""
echo -e "${GREEN}✅ Session complete!${NC}"
echo "Summary saved to: $SUMMARY_FILE"
echo ""
echo "Statistics:"
echo "- Commits this session: $(git log --oneline --since='1 hour ago' | wc -l)"
echo "- Files changed: $(git diff --stat HEAD~1 2>/dev/null | tail -1 | cut -d' ' -f2 || echo "0")"
echo ""
echo "===================================="
