version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: podcast_production_db
    environment:
      POSTGRES_DB: podcast_production
      POSTGRES_USER: podcast_app
      # CHANGE THIS PASSWORD IN PRODUCTION!
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me_in_production}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U podcast_app -d podcast_production"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: podcast_production_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@localhost}
      # CHANGE THIS PASSWORD IN PRODUCTION!
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-change_me_in_production}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - postgres
    profiles:
      - admin
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local