title = "ai-podcasts-nobody-knows gitleaks config"

[allowlist]
description = "Ignore generated/local artifacts and common false positives"
paths = [
  "audio-output/.*",
  "nobody-knows/output/.*",
  "\\.claude/mcp-servers/.*",
  "\\.secrets\\.baseline",
  "node_modules/",
  "dist/",
  "build/",
  ".claude/mocks/",
  "projects/.*/output/"
]
regexes = []
commits = []
