# Production Hardening Configuration - Claude Code Native
# Version: 1.0.0
# Purpose: Security, reliability, and operational hardening settings
# FOLLOWS CLAUDE CODE NATIVE PATTERNS - NO CUSTOM FRAMEWORKS

security:
  api_keys:
    validation:
      enabled: true
      on_startup: mandatory
      check_interval: 300  # seconds
    protection:
      mask_in_logs: true
      encrypt_at_rest: false  # Use OS keychain instead
      rotate_days: 90
    enforcement:
      missing_key_action: "abort"
      invalid_key_action: "abort"
      expired_key_action: "alert"
  
  input_validation:
    max_input_length: 50000  # characters
    max_topic_length: 500
    allowed_characters: "alphanumeric, spaces, punctuation"
    sql_injection_check: true
    xss_prevention: true
    command_injection_check: true
    
  rate_limiting:
    api_calls:
      perplexity:
        per_minute: 30
        per_hour: 500
        burst_size: 10
      elevenlabs:
        per_minute: 10
        per_hour: 100
        burst_size: 3
      anthropic:
        per_minute: 60
        per_hour: 1000
        burst_size: 20
    
  audit_logging:
    enabled: true
    log_api_calls: true
    log_config_changes: true
    log_errors: true
    log_security_events: true
    retention_days: 90
    
reliability:
  error_handling:
    retry_strategy:
      max_attempts: 3
      backoff_type: "exponential"
      initial_delay: 1  # seconds
      max_delay: 60
      jitter: true
    
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      reset_timeout: 300  # seconds
      half_open_requests: 2
    
    fallback:
      use_cache: true
      degraded_mode: true
      alert_on_fallback: true
  
  resource_limits:
    memory:
      max_mb: 2048
      warning_threshold_mb: 1536
      action_on_exceed: "garbage_collect"
    
    disk:
      max_gb: 10
      warning_threshold_gb: 8
      cleanup_threshold_gb: 9
      action_on_exceed: "cleanup_old_sessions"
    
    concurrent_operations:
      max_agents: 5
      max_api_calls: 10
      queue_overflow_action: "reject"
  
  health_checks:
    enabled: true
    interval_seconds: 60
    checks:
      - mcp_connectivity
      - api_key_validity
      - disk_space
      - memory_usage
      - error_rate
    
    thresholds:
      error_rate_percent: 5
      response_time_ms: 5000
      memory_usage_percent: 75
      disk_usage_percent: 80

operations:
  monitoring:
    metrics:
      enabled: true
      collect_interval: 30  # seconds
      metrics_to_collect:
        - api_latency
        - error_rate
        - cost_per_operation
        - quality_scores
        - resource_usage
    
    alerting:
      enabled: true
      channels:
        - console
        - log_file
      
      alerts:
        - name: "High Error Rate"
          condition: "error_rate > 5%"
          severity: "critical"
        - name: "Budget Exceeded"
          condition: "daily_cost > $33.25"
          severity: "critical"
        - name: "API Key Expiring"
          condition: "days_to_expiry < 7"
          severity: "warning"
        - name: "High Memory Usage"
          condition: "memory_percent > 85"
          severity: "warning"
  
  session_management:
    checkpoint_interval: 300  # seconds
    max_session_age: 86400  # 24 hours
    cleanup_old_sessions: true
    archive_completed: true
    
  performance:
    cache:
      enabled: true
      ttl_seconds: 3600
      max_entries: 1000
      cache_research: true
      cache_scripts: false  # Always regenerate for freshness
    
    optimization:
      parallel_research: true
      batch_operations: true
      compress_logs: true
      optimize_context: true

validation:
  pre_production:
    required_checks:
      - all_api_keys_configured
      - mcp_servers_connected
      - voice_id_correct
      - quality_gates_configured
      - hooks_executable
      - logs_writable
    
  runtime:
    continuous_validation:
      - api_availability
      - cost_tracking_active
      - quality_thresholds_met
      - error_rate_acceptable
    
  post_production:
    validation_reports:
      - cost_analysis
      - quality_metrics
      - error_summary
      - performance_stats

# Claude Code Native Patterns Enforcement
claude_code_compliance:
  enforce_patterns:
    - direct_agent_invocation  # No Task tool
    - mcp_inheritance  # No hardcoded tools
    - bash_hooks_only  # No Python/JS hooks
    - selective_context  # <15K token files
    - command_orchestration  # Commands don't implement
  
  forbidden_patterns:
    - task_tool_usage
    - custom_frameworks
    - hardcoded_api_calls
    - monolithic_contexts
    - non_bash_hooks
  
  validation_on:
    - pre_commit
    - pull_request
    - production_deploy