# Base configuration for AI Podcast Production System
# Version: 1.0.0
# Date: August 2025

system:
  name: "AI Podcast Production System"
  version: "1.0.0"
  environment: "${PODCAST_ENV:development}"
  temporal_context: "August 2025"

# Cost and budget settings
budget:
  episode_limit: 10.00
  warning_threshold: 7.50
  research_budget: 2.50
  script_budget: 3.00
  audio_budget: 2.00
  validation_budget: 0.50

# Quality thresholds
quality:
  minimum_score: 8.5
  target_score: 9.0
  brand_alignment_threshold: 0.85
  technical_accuracy_threshold: 0.90
  engagement_threshold: 0.80

# Retry and timeout settings
execution:
  max_retries: 3
  retry_delay: 2
  timeout_seconds: 300
  max_parallel_agents: 5

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/podcast_production.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Feature flags
features:
  enable_a_b_testing: true
  enable_cost_optimization: true
  enable_quality_gates: true
  enable_observability: true
  enable_caching: true

# Cache settings
cache:
  ttl_seconds: 3600
  max_size_mb: 100
  provider: "redis"
  redis_url: "${REDIS_URL:redis://localhost:6379}"
