# ==============================================================================
# AI PODCAST PRODUCTION - PRODUCTION CONFIGURATION
# ==============================================================================
# Version: 1.0.0 | Date: September 2025
# Production-ready configuration with comprehensive monitoring and safety controls

system:
  name: "AI Podcast Production System"
  version: "1.0.0"
  environment: "production"
  temporal_context: "September 2025"
  deployment_date: "2025-09-01"

# ==============================================================================
# PRODUCTION BUDGET CONTROLS (CRITICAL SAFETY MEASURES)
# ==============================================================================

budget:
  # Episode-level budget controls
  episode_limit: 5.51  # Maximum cost per episode (USD)
  warning_threshold: 4.50  # Alert threshold (USD)
  emergency_stop: 6.00  # Emergency stop threshold (USD)
  
  # Component-specific budget allocation
  research_budget: 2.00
  script_budget: 2.00
  audio_budget: 1.00
  validation_budget: 0.51
  
  # System-wide budget controls
  daily_limit: 50.00
  weekly_limit: 200.00
  monthly_limit: 1000.00
  
  # Budget monitoring and alerts
  monitoring:
    enable_alerts: true
    alert_thresholds: [50, 75, 90, 100]  # Percentage of budget used
    alert_channels: ["email", "slack", "discord"]
    cost_tracking_precision: 0.01  # Track to penny precision
    
  # Emergency procedures
  emergency:
    auto_stop_on_overrun: true
    admin_notification_required: true
    recovery_approval_needed: true

# ==============================================================================
# PRODUCTION QUALITY GATES AND STANDARDS
# ==============================================================================

quality:
  # Minimum quality thresholds (reject below these scores)
  minimum_scores:
    brand_alignment: 0.85
    technical_accuracy: 0.90
    engagement: 0.80
    overall_quality: 8.5
    
  # Target quality scores (optimal performance)
  target_scores:
    brand_alignment: 0.95
    technical_accuracy: 0.95
    engagement: 0.90
    overall_quality: 9.2
    
  # Quality control mechanisms
  controls:
    enable_quality_gates: true
    reject_below_threshold: true
    max_quality_retries: 2
    quality_reviewer_required: false
    multi_evaluator_consensus: true
    
  # Quality metrics tracking
  metrics:
    track_quality_trends: true
    quality_degradation_alerts: true
    performance_benchmarking: true

# ==============================================================================
# PRODUCTION EXECUTION CONTROLS
# ==============================================================================

execution:
  # Resource limits and timeouts
  max_retries: 3
  retry_delay_seconds: 5
  timeout_seconds: 1200  # 20 minutes max per episode
  max_parallel_agents: 3
  
  # Performance optimization
  enable_caching: true
  cache_ttl_seconds: 3600
  max_cache_size_mb: 500
  enable_batch_processing: true
  
  # Error handling and recovery
  error_handling:
    auto_retry_on_failure: true
    graceful_degradation: true
    maintain_state_on_error: true
    comprehensive_error_logging: true
    
  # Resource monitoring
  monitoring:
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    network_timeout: 30

# ==============================================================================
# PRODUCTION LOGGING AND OBSERVABILITY
# ==============================================================================

logging:
  # Log levels and formatting
  level: "INFO"
  format: "json"  # Structured logging for production
  include_correlation_id: true
  include_user_context: true
  
  # Log destinations
  destinations:
    file:
      path: "logs/podcast_production.log"
      max_size_mb: 100
      backup_count: 10
      rotation: "daily"
    console:
      enabled: true
      level: "WARNING"
    external:
      sentry:
        enabled: true
        environment: "production"
        capture_unhandled: true
      langfuse:
        enabled: true
        trace_all_operations: true
        
  # Audit logging
  audit:
    enabled: true
    log_api_calls: true
    log_cost_changes: true
    log_quality_decisions: true
    log_security_events: true

# ==============================================================================
# PRODUCTION MONITORING AND ALERTING
# ==============================================================================

monitoring:
  # Real-time metrics collection
  metrics:
    enabled: true
    collection_interval: 60  # seconds
    retention_days: 90
    
  # Key performance indicators
  kpis:
    - name: "episode_production_success_rate"
      target: 0.95
      alert_below: 0.90
    - name: "average_episode_cost"
      target: 5.51
      alert_above: 6.00
    - name: "quality_score_average"
      target: 9.0
      alert_below: 8.5
    - name: "production_time_minutes"
      target: 15
      alert_above: 25
      
  # Alerting configuration
  alerts:
    channels:
      email:
        enabled: true
        smtp_server: "${SMTP_SERVER}"
        recipients: ["${ADMIN_EMAIL}"]
      slack:
        enabled: true
        webhook_url: "${SLACK_WEBHOOK}"
        channel: "#podcast-alerts"
      discord:
        enabled: false
        webhook_url: "${DISCORD_WEBHOOK}"
        
    # Alert severity levels
    severity_levels:
      critical: ["budget_overrun", "quality_failure", "system_down"]
      warning: ["budget_threshold", "quality_degradation", "performance_slow"]
      info: ["episode_complete", "milestone_reached"]

# ==============================================================================
# PRODUCTION SECURITY CONFIGURATION
# ==============================================================================

security:
  # API key management
  api_keys:
    rotation_days: 90
    encryption_at_rest: true
    secure_storage: true
    audit_access: true
    
  # Access control
  access_control:
    rate_limiting:
      enabled: true
      requests_per_minute: 100
      burst_allowance: 20
    authentication:
      jwt_expiry_hours: 24
      refresh_token_enabled: true
      multi_factor_required: false
      
  # Data protection
  data_protection:
    encrypt_sensitive_data: true
    anonymize_logs: true
    gdpr_compliance: true
    data_retention_days: 365

# ==============================================================================
# PRODUCTION FEATURE CONFIGURATION
# ==============================================================================

features:
  # Core production features
  core:
    enable_cost_optimization: true
    enable_quality_gates: true
    enable_observability: true
    enable_caching: true
    enable_metrics: true
    enable_tracing: true
    
  # Advanced features
  advanced:
    enable_a_b_testing: true
    enable_multi_model_ensemble: false
    enable_real_time_monitoring: true
    enable_predictive_scaling: false
    
  # Experimental features (disabled in production)
  experimental:
    enable_experimental_agents: false
    enable_beta_models: false
    enable_debug_mode: false

# ==============================================================================
# PRODUCTION BACKUP AND DISASTER RECOVERY
# ==============================================================================

backup:
  # Automated backup configuration
  schedule:
    frequency: "daily"
    time: "02:00"
    timezone: "UTC"
    
  # Backup destinations
  destinations:
    local:
      enabled: true
      path: "/backup/podcast_production"
      retention_days: 30
    cloud:
      enabled: true
      provider: "aws_s3"
      bucket: "${BACKUP_S3_BUCKET}"
      encryption: true
      
  # Backup verification
  verification:
    enabled: true
    test_restore_frequency: "weekly"
    integrity_checks: true
    
  # Disaster recovery
  disaster_recovery:
    rto_minutes: 60  # Recovery Time Objective
    rpo_minutes: 15  # Recovery Point Objective
    hot_standby_enabled: false
    cross_region_backup: true

# ==============================================================================
# PRODUCTION PERFORMANCE CONFIGURATION
# ==============================================================================

performance:
  # System resource allocation
  resources:
    max_memory_gb: 8
    max_cpu_cores: 4
    max_disk_gb: 100
    
  # Optimization settings
  optimization:
    connection_pooling: true
    query_optimization: true
    cache_warming: true
    precompute_common_requests: true
    
  # Load balancing
  load_balancing:
    enabled: false  # Single instance for initial production
    min_instances: 1
    max_instances: 3
    scale_up_threshold: 75
    scale_down_threshold: 25

# ==============================================================================
# PRODUCTION VALIDATION AND HEALTH CHECKS
# ==============================================================================

health_checks:
  # System health monitoring
  intervals:
    fast_check_seconds: 30    # Basic system status
    deep_check_minutes: 5     # Comprehensive system check
    dependency_check_minutes: 10  # External service checks
    
  # Health check endpoints
  endpoints:
    - name: "system_status"
      path: "/health"
      expected_response: 200
    - name: "api_connectivity"
      path: "/health/apis"
      expected_response: 200
    - name: "cost_tracking"
      path: "/health/costs"
      expected_response: 200
      
  # Dependency health checks
  dependencies:
    - service: "openrouter_api"
      check_interval: 300
      timeout_seconds: 10
    - service: "elevenlabs_api"
      check_interval: 300
      timeout_seconds: 15
    - service: "perplexity_api"
      check_interval: 300
      timeout_seconds: 10

# ==============================================================================
# PRODUCTION DEPLOYMENT CONFIGURATION
# ==============================================================================

deployment:
  # Environment specifications
  environment:
    python_version: "3.11+"
    os_requirements: ["linux", "macos"]
    minimum_memory_gb: 4
    minimum_disk_gb: 50
    
  # Deployment validation
  validation:
    pre_deployment_tests: true
    post_deployment_verification: true
    rollback_on_failure: true
    canary_deployment: false
    
  # Production readiness checklist
  readiness_checklist:
    api_keys_configured: false
    budget_limits_set: false
    quality_thresholds_defined: false
    monitoring_configured: false
    alerts_tested: false
    backup_verified: false
    security_reviewed: false
    performance_tested: false
    documentation_complete: false
    team_trained: false

# ==============================================================================
# PRODUCTION MAINTENANCE WINDOWS
# ==============================================================================

maintenance:
  # Scheduled maintenance windows
  windows:
    daily:
      start_time: "02:00"
      duration_minutes: 30
      timezone: "UTC"
      activities: ["log_rotation", "cache_cleanup", "metrics_aggregation"]
    weekly:
      day: "sunday"
      start_time: "01:00"
      duration_hours: 2
      activities: ["full_backup", "security_updates", "performance_optimization"]
    monthly:
      day_of_month: 1
      start_time: "00:00"
      duration_hours: 4
      activities: ["system_updates", "dependency_updates", "security_audit"]
      
  # Emergency maintenance
  emergency:
    max_downtime_minutes: 15
    notification_required: true
    approval_required: true
    rollback_plan_required: true

# ==============================================================================
# END OF PRODUCTION CONFIGURATION
# ==============================================================================

# Configuration validation
config_version: "1.0.0"
last_updated: "2025-09-01"
validated_by: "production_setup_system"
next_review_date: "2025-10-01"