# AI Podcasts Production Configuration - Single Source of Truth
# This is the authoritative configuration for all production settings

production:
  project_name: "Nobody Knows"
  tagline: "Exploring the frontiers of human knowledge with intellectual humility"
  
quality_gates:
  # Reference to existing quality gates configuration
  config_path: "projects/nobody-knows/config/quality_gates.json"
  
  # Quick reference thresholds (authoritative values in JSON)
  thresholds:
    comprehension: 0.85
    brand_consistency: 0.90
    engagement: 0.80
    technical: 0.85
    overall: 0.85

episode_specifications:
  duration:
    target_minutes: 27
    minimum_minutes: 25
    maximum_minutes: 30
  
  word_count:
    target: 4000
    minimum: 3900
    maximum: 4100
  
  reading_pace:
    words_per_minute: 145
    pause_allowance: 0.05  # 5% for pauses
  
  structure:
    segments:
      minimum: 3
      maximum: 7
      target: 5

cost_optimization:
  budget_per_episode:
    total: 9.00
    breakdown:
      research: 3.00
      script_writing: 2.50
      quality_evaluation: 0.50
      audio_synthesis: 2.00  # Future allocation
      buffer: 1.00
  
  cost_targets:
    production_target: 5.00  # Optimization goal
    maximum_acceptable: 9.00
  
  model_selection:
    research: "sonnet"  # Complex reasoning
    script_writing: "sonnet"  # Creative narrative
    quality_evaluation: "haiku"  # Quick validation
    audio_synthesis: "external"  # ElevenLabs future

brand_voice:
  style_fusion:
    primary: "Richard Feynman"  # Clarity through analogies
    secondary: "Lex Fridman"  # Technical curiosity
    balance: "accessibility_first"
  
  intellectual_humility:
    phrases_per_1000_words: 5
    minimum_per_1000_words: 3
    examples:
      - "We're still figuring out"
      - "Nobody fully understands"
      - "Here's what we think we know"
      - "The mystery deepens"
      - "Scientists are still debating"
  
  curiosity_markers:
    questions_per_1000_words: 4
    minimum_per_1000_words: 2
    types:
      - "What if..."
      - "Why does..."
      - "How might..."
      - "Could it be that..."
  
  accessibility:
    complexity_progression: "simple_to_complex"
    analogy_layers: 3  # Universal, Professional, Historical
    jargon_policy: "translate_immediately"
    assumption_level: "zero_knowledge_start"

audio_optimization:
  tts_provider: "ElevenLabs"  # Future integration
  tts_version: "Turbo v2"
  
  ssml_elements:
    breaks:
      short: "0.3s"
      medium: "0.5s"
      long: "0.7s"
      maximum: "1.0s"
    
    prosody:
      rate_variation: "90-110%"
      pitch_variation: "-5% to +5%"
      volume: "medium"
  
  formatting_rules:
    numbers: "spell_out"  # "twenty twenty-five"
    percentages: "spell_out"  # "ninety-nine percent"
    abbreviations: "expand"  # "application programming interface"
    symbols: "describe"  # "leads to" not "→"

output_directories:
  # IMPORTANT: All production outputs go to projects folder, NOT .claude
  base_output: "projects/nobody-knows/output"
  
  structure:
    research: "projects/nobody-knows/output/research"
    scripts: "projects/nobody-knows/output/scripts"  
    quality_reports: "projects/nobody-knows/output/quality"
    audio: "projects/nobody-knows/output/audio"  # Future
    sessions: "projects/nobody-knows/output/sessions"
    archives: "projects/nobody-knows/output/archives"
  
  naming_conventions:
    research_package: "ep{number}_research_{topic}_{date}.md"
    script: "ep{number}_script_{topic}_{date}.md"
    quality_report: "ep{number}_quality_{date}.json"
    session_file: "ep{number}_session_{date}.json"

session_management:
  session_id_format: "ep_{number}_{YYYYMMDD}_{HHMM}"
  
  # Sessions are tracked in output directory, not .claude
  session_directory: "projects/nobody-knows/output/sessions"
  
  tracking:
    progress_updates: true
    cost_monitoring: true
    quality_checkpoints: true
    error_logging: true
  
  state_persistence:
    save_frequency: "after_each_agent"
    backup_enabled: true
    retention_days: 30

agent_coordination:
  pipeline:
    - agent: "research-coordinator"
      timeout_minutes: 30
      retry_on_failure: true
      max_retries: 2
    
    - agent: "script-writer"
      timeout_minutes: 20
      retry_on_failure: true
      max_retries: 2
    
    - agent: "quality-evaluator"
      timeout_minutes: 10
      retry_on_failure: true
      max_retries: 3
    
    - agent: "audio-synthesizer"
      enabled: false  # Future implementation
      timeout_minutes: 15
  
  handoff:
    format: "structured_json"
    validation_required: true
    quality_gates_check: true

progressive_complexity:
  season_1:
    episodes: "1-10"
    complexity_level: "1-3"
    focus: "foundation_building"
    audience: "complete_beginners"
  
  season_2:
    episodes: "11-25"
    complexity_level: "3-5"
    focus: "intermediate_exploration"
    audience: "developing_understanding"
  
  season_3_plus:
    episodes: "26+"
    complexity_level: "5-10"
    focus: "advanced_topics_accessible"
    audience: "established_foundation"

monitoring:
  metrics:
    - name: "episode_production_time"
      target: "<2 hours"
      alert_threshold: "3 hours"
    
    - name: "first_pass_quality_rate"
      target: ">90%"
      alert_threshold: "75%"
    
    - name: "cost_per_episode"
      target: "<$5.00"
      alert_threshold: "$7.00"
    
    - name: "brand_consistency_score"
      target: ">0.90"
      alert_threshold: "0.85"
  
  dashboards:
    production_overview: true
    quality_trends: true
    cost_analysis: true
    agent_performance: true

# Template References
# Use these in agents and commands to avoid duplication
templates:
  episode_title: "Episode {number}: {hook_title}"
  research_package: ".claude/shared/templates/research-package.json"
  script_template: ".claude/shared/templates/script-structure.md"
  quality_report: ".claude/shared/templates/quality-report.json"

# Constants for Reference
# Use {{CONSTANT_NAME}} pattern in documents
constants:
  PROJECT_NAME: "Nobody Knows"
  QUALITY_THRESHOLD: 0.85
  BRAND_CONSISTENCY_TARGET: 0.90
  EPISODE_DURATION: 27
  COST_TARGET: 5.00
  WPM_READING_PACE: 145