# Version Manifest Schema for Level-1-Dev Components
# Defines the structure for version tracking across all components

schema_version: "1.0.0"
schema_type: "version-manifest"

# Component type definitions
component_types:
  - agent
  - command
  - template
  - workflow
  - quality
  - test
  - hook
  - library

# Version format: MAJOR.MINOR.PATCH
# Following Semantic Versioning 2.0.0
version_format:
  pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
  increment_rules:
    major: "Breaking changes that require migration"
    minor: "New features, backward compatible"
    patch: "Bug fixes and minor improvements"

# Manifest structure for each component
component_manifest:
  # Required fields
  required:
    name:
      type: string
      description: "Component unique identifier"
      pattern: "^[a-z][a-z0-9-]*$"

    type:
      type: enum
      description: "Component type from component_types"
      values: component_types

    version:
      type: string
      description: "Current semantic version"
      pattern: version_format.pattern

    created:
      type: date
      description: "Initial creation date"
      format: "YYYY-MM-DD"

    updated:
      type: date
      description: "Last modification date"
      format: "YYYY-MM-DD"

    status:
      type: enum
      description: "Current component status"
      values:
        - active
        - deprecated
        - archived
        - experimental

  # Optional fields
  optional:
    author:
      type: string
      description: "Component creator"

    description:
      type: string
      description: "Brief component description"

    dependencies:
      type: array
      description: "List of component dependencies"
      items:
        name: string
        version: string
        type: enum

    changelog:
      type: array
      description: "Version history"
      items:
        version: string
        date: date
        changes: array[string]
        breaking: boolean

    compatibility:
      type: object
      description: "Compatibility requirements"
      properties:
        min_claude_version: string
        max_claude_version: string
        required_tools: array[string]

    migration:
      type: object
      description: "Migration information"
      properties:
        from_version: string
        to_version: string
        script: string
        auto_migrate: boolean

    checksum:
      type: string
      description: "File integrity checksum"
      format: "sha256"

    tags:
      type: array
      description: "Categorization tags"
      items: string

    metrics:
      type: object
      description: "Usage and performance metrics"
      properties:
        usage_count: integer
        success_rate: float
        avg_duration: float
        last_used: date

# Validation rules
validation_rules:
  - rule: "version_increment"
    description: "Version must increment appropriately"
    check: "new_version > old_version"

  - rule: "dependency_exists"
    description: "All dependencies must exist"
    check: "dependency.name in manifest"

  - rule: "backward_compatibility"
    description: "Minor/patch versions maintain compatibility"
    check: "major_version unchanged for minor/patch"

  - rule: "status_transition"
    description: "Valid status transitions only"
    allowed:
      experimental: [active, deprecated, archived]
      active: [deprecated, archived]
      deprecated: [archived]
      archived: []

# Example component manifest
example:
  name: "agent-builder"
  type: "command"
  version: "1.2.3"
  created: "2024-01-15"
  updated: "2024-08-16"
  status: "active"
  author: "level-1-dev-team"
  description: "Creates new agents with consistent structure"
  dependencies:
    - name: "agent-template"
      version: "1.0.0"
      type: "template"
  changelog:
    - version: "1.2.3"
      date: "2024-08-16"
      changes:
        - "Fixed template validation"
        - "Added error recovery"
      breaking: false
    - version: "1.2.0"
      date: "2024-08-01"
      changes:
        - "Added quality gates"
        - "New testing framework"
      breaking: false
    - version: "1.0.0"
      date: "2024-01-15"
      changes:
        - "Initial release"
      breaking: false
  compatibility:
    min_claude_version: "2.0.0"
    required_tools:
      - "Read"
      - "Write"
      - "TodoWrite"
  tags:
    - "meta-development"
    - "agent-creation"
    - "core-tool"
